config/routes.rb
Rails.application.routes.draw do
  resources :horses
  resources :cars
  resources :trains
  resources :airplanes

end

app/models/airplane.rb
class Airplane < ActiveRecord::Base
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/horse.rb
class Horse < ActiveRecord::Base
end

app/models/train.rb
class Train < ActiveRecord::Base
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  def index
    @airplanes = Airplane.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end 
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: [:show, :edit, :update, :destroy]

  # GET /horses
  # GET /horses.json
  def index
    @horses = Horse.all
  end

  # GET /horses/1
  # GET /horses/1.json
  def show
  end

  # GET /horses/new
  def new
    @horse = Horse.new
  end

  # GET /horses/1/edit
  def edit
  end

  # POST /horses
  # POST /horses.json
  def create
    @horse = Horse.new(horse_params)

    respond_to do |format|
      if @horse.save
        format.html { redirect_to @horse, notice: 'Horse was successfully created.' }
        format.json { render :show, status: :created, location: @horse }
      else
        format.html { render :new }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horses/1
  # PATCH/PUT /horses/1.json
  def update
    respond_to do |format|
      if @horse.update(horse_params)
        format.html { redirect_to @horse, notice: 'Horse was successfully updated.' }
        format.json { render :show, status: :ok, location: @horse }
      else
        format.html { render :edit }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horses/1
  # DELETE /horses/1.json
  def destroy
    @horse.destroy
    respond_to do |format|
      format.html { redirect_to horses_url, notice: 'Horse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horse
      @horse = Horse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def horse_params
      params.require(:horse).permit(:name)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index
    @trains = Train.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/airplanes/index.html.erb
<h1>Airplanes#index</h1>
<p>Find me in app/views/airplanes/index.html.erb</p>
<ul>
  <% @airplanes.each do |airplane| %>
  <li> <%= airplane.name %> </li>
  <% end %>
</ul>

app/views/cars/index.html.erb
<h1>Cars#index</h1>
<p>Find me in app/views/cars/index.html.erb</p>
<ul>
  <% @cars.each do |car| %>
  <li> <%= car.name %> </li>
  <% end %>
</ul>

app/views/horses/_form.html.erb
<%= form_for(@horse) do |f| %>
  <% if @horse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
      <% @horse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/horses/edit.html.erb
<h1>Editing Horse</h1>

<%= render 'form' %>

<%= link_to 'Show', @horse %> |
<%= link_to 'Back', horses_path %>

app/views/horses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Horses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @horses.each do |horse| %>
      <tr>
        <td><%= horse.name %></td>
        <td><%= link_to 'Show', horse %></td>
        <td><%= link_to 'Edit', edit_horse_path(horse) %></td>
        <td><%= link_to 'Destroy', horse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Horse', new_horse_path %>

app/views/horses/new.html.erb
<h1>New Horse</h1>

<%= render 'form' %>

<%= link_to 'Back', horses_path %>

app/views/horses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @horse.name %>
</p>

<%= link_to 'Edit', edit_horse_path(@horse) %> |
<%= link_to 'Back', horses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/trains/index.html.erb
<h1>Trains#index</h1>
<p>Find me in app/views/trains/index.html.erb</p>
<ul>
  <% @trains.each do |train| %>
  <li> <%= train.name %> </li>
  <% end %>
</ul>